import type { ExerciseId } from '@/shared/data/exercises';

export const TECHNIQUE_PATTERNS = [
  'flatPress',
  'inclinePress',
  'overheadPress',
  'raise',
  'rearDelt',
  'uprightRow',
  'fly',
  'dip',
  'pushUp',
  'tricepsExtension',
  'verticalPull',
  'row',
  'deadlift',
  'curl',
  'squat',
  'legPress',
  'hinge',
  'lunge',
  'legExtension',
  'calfRaise',
  'plank',
] as const;
export type TechniquePattern = (typeof TECHNIQUE_PATTERNS)[number];

/** Exercises sharing a movement share their technique cues (`exercises:technique.<pattern>`). */
export const TECHNIQUE_OF: Record<ExerciseId, TechniquePattern> = {
  'bench-press': 'flatPress',
  'close-grip-bench-press': 'flatPress',
  'incline-dumbbell-press': 'inclinePress',
  'dumbbell-shoulder-press': 'overheadPress',
  'seated-shoulder-press': 'overheadPress',
  'arnold-press': 'overheadPress',
  'lateral-raise': 'raise',
  'front-raise': 'raise',
  'reverse-fly': 'rearDelt',
  'face-pull': 'rearDelt',
  'upright-row': 'uprightRow',
  'cable-crossover': 'fly',
  dip: 'dip',
  'push-up': 'pushUp',
  'triceps-pushdown': 'tricepsExtension',
  'french-press': 'tricepsExtension',
  'pull-up': 'verticalPull',
  'chin-up': 'verticalPull',
  'lat-pulldown': 'verticalPull',
  'seated-cable-row': 'row',
  't-bar-row': 'row',
  deadlift: 'deadlift',
  'hammer-curl': 'curl',
  'dumbbell-curl': 'curl',
  squat: 'squat',
  'hack-squat': 'squat',
  'leg-press': 'legPress',
  'romanian-deadlift': 'hinge',
  lunge: 'lunge',
  'leg-extension': 'legExtension',
  'calf-raise': 'calfRaise',
  plank: 'plank',
};
