-- Support tickets with chat messages, plus body-check photos and metrics.

create table public.tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  -- Human-readable "#1042"; assigned by the server, synced back to the client.
  number int generated by default as identity (start with 1000),
  kind text not null check (kind in ('bug', 'idea')),
  status text not null default 'open' check (status in ('open', 'planned', 'resolved', 'closed')),
  priority int check (priority between 1 and 5),
  subject text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create table public.ticket_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  ticket_id uuid not null references public.tickets (id) on delete cascade,
  author text not null default 'user' check (author in ('user', 'team')),
  body text not null default '',
  -- Storage paths in the ticket-attachments bucket.
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.body_check_photos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  body_check_id uuid not null references public.body_checks (id) on delete cascade,
  pose text not null check (pose in ('front', 'left', 'right', 'back')),
  -- Path in the body-checks storage bucket; null until the upload finished.
  storage_path text,
  created_at timestamptz not null default now()
);

alter table public.body_checks add column metrics jsonb not null default '{}'::jsonb;

create index on public.tickets (user_id, updated_at desc);
create index on public.ticket_messages (ticket_id, created_at);
create index on public.body_check_photos (body_check_id);

do $$
declare t text;
begin
  foreach t in array array['tickets', 'ticket_messages', 'body_check_photos'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy "own rows" on public.%I for all to authenticated
         using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t);
  end loop;
end $$;

-- Users may only write their own messages; team replies are inserted server-side.
create policy "users write user messages" on public.ticket_messages
  as restrictive for insert to authenticated with check (author = 'user');

alter publication powersync add table public.tickets, public.ticket_messages, public.body_check_photos;

-- Private buckets; objects live under "<user id>/...".
insert into storage.buckets (id, name, public)
values ('ticket-attachments', 'ticket-attachments', false), ('body-checks', 'body-checks', false)
on conflict (id) do nothing;

create policy "own files" on storage.objects for all to authenticated
  using (
    bucket_id in ('ticket-attachments', 'body-checks')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id in ('ticket-attachments', 'body-checks')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
